version: '3.8'

services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: subhojeet992012/vprofiledb
    container_name: vprodb
    ports:
      - 3306:3306
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vproddbpass

  vprocache01:
    image: memcached
    container_name: vprocache01

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672

  vproapp:
    build:
      context: ./Docker-files/app
    image: subhojeet992012/vprofileapp
    container_name: vproapp
    ports:
      - 8080:8080
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: subhojeet992012/vprofileweb
    container_name: vproweb
    ports:
      - 80:80

volumes:
  vproappdata: {}
  vprodbdata: {}
